name: floras tests conda env - Ubuntu
on:
  push:
  pull_request:

jobs:
  create-env:
    name: Testing conda env (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10","3.11","3.12"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create environment with conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Check conda
        run: |
            conda info
            conda list

      - name: Install spot
        run: conda install -c conda-forge spot

      - name: Add pdm
        run: pip install pdm

      - name: Install package
        run: pdm install

      - name : Install Package for Testing
        run : conda install pytest

      - name : Run tests
        run : pdm run pytest -v tests
