---
# configuration for GitHub Actions
name: floras tests in PDM env - MacOS
on:
    push:
    pull_request:

jobs:
    build:
        name: Build and test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: ["macos-latest"]
                python-version: [
                    '3.10',
                    '3.11',
                    '3.12'
                ]
        steps:
            - uses: actions/checkout@v4
            - uses: pdm-project/setup-pdm@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: true

            - name: Install Python dependencies
              run: |
                pdm install -v
            - name: Try to use cached Spot
              id: cache-spot
              uses: actions/cache@v4
              with:
                  path: spot-2.12
                  key: ${{ runner.os }}-${{ matrix.python-version }}-spot-${{ hashFiles('get_spot.py') }}-${{ hashFiles('pyproject.toml') }}
            - name: Install Spot
              if: steps.cache-spot.outputs.cache-hit == 'true'
              run: |
                cd spot-2.12
                make install
            - name: Build and install Spot
              if: steps.cache-spot.outputs.cache-hit != 'true'
              run: |
                pdm run python get_spot.py
            - name: Run tests
              run: |
                pdm run pytest -v tests
